branch-defaults:
  master:
    environment: admin-wearefriends-today-prod
environment-defaults:
  admin-wearefriends-today-prod:
    branch: null
    repository: null
global:
  application_name: admin.wearefriends.today
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: deployment-manager
  sc: git
  workspace_type: Application
